
import type { Article } from '@/types';

// In a real application, the 'excerpt' might be generated by an AI model:
// import { summarizeArticle } from '@/ai/flows/article-summarizer';
// const summaryData = await summarizeArticle({ articleContent: article.content });
// article.excerpt = summaryData.summary;
// For this scaffold, excerpts are pre-defined.

const articles: Article[] = [
  {
    slug: 'the-future-of-remote-work',
    title: 'The Evolving Landscape of Remote Work in the 21st Century',
    datePublished: '2024-07-15',
    author: 'Jane Doe',
    category: 'Productivity',
    imageUrl: 'https://placehold.co/1200x600.png',
    imageHint: 'modern office',
    content: `
      <p class="mb-4">The COVID-19 pandemic accelerated a trend that was already gaining momentum: remote work. What started as a temporary measure for many has evolved into a permanent or hybrid model for countless organizations worldwide. This shift has profound implications for employees, employers, and the economy at large.</p>
      <h2 class="text-2xl font-headline mt-6 mb-3">Benefits of Remote Work</h2>
      <p class="mb-4">For employees, the benefits are numerous. Increased flexibility, no commute time, and the ability to create a personalized work environment are often cited. Many report a better work-life balance, though this can vary depending on individual circumstances and company culture.</p>
      <img src="https://placehold.co/800x400.png" alt="Remote work setup" class="my-6 rounded-lg shadow-md" data-ai-hint="home office" />
      <p class="mb-4">Employers, too, can reap rewards. Access to a global talent pool, reduced overhead costs associated with office space, and potentially increased productivity are significant advantages. However, managing a distributed workforce presents its own set of challenges.</p>
      <h2 class="text-2xl font-headline mt-6 mb-3">Challenges and Considerations</h2>
      <p class="mb-4">Maintaining company culture, ensuring effective communication, and addressing potential feelings of isolation among remote employees are key concerns. Technology plays a crucial role in mitigating these challenges, with a plethora of tools available for collaboration, project management, and virtual team building.</p>
      <p class="mb-4">The future of work is likely to be a hybrid model for many, combining the benefits of remote flexibility with the advantages of in-person collaboration. Finding the right balance will be critical for organizational success in the years to come.</p>
    `,
    excerpt: 'Explore the profound shifts in work culture as remote and hybrid models become the new norm, offering flexibility but also presenting new challenges for companies and employees alike.',
    isFeatured: true,
    tags: ['remote work', 'future', 'productivity'],
  },
  {
    slug: 'mindful-living-in-a-digital-age',
    title: 'Cultivating Mindfulness in Our Hyperconnected World',
    datePublished: '2024-07-10',
    author: 'John Smith',
    category: 'Wellness',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'meditation nature',
    content: `
      <p class="mb-4">In an era dominated by screens and constant notifications, finding moments of peace and presence can feel like a luxury. Mindfulness, the practice of paying attention to the present moment without judgment, offers a powerful antidote to the stresses of modern life.</p>
      <h2 class="text-2xl font-headline mt-6 mb-3">The Science of Mindfulness</h2>
      <p class="mb-4">Research has shown that regular mindfulness practice can reduce stress, improve focus, and enhance emotional regulation. It's not about emptying the mind, but rather about observing thoughts and feelings as they arise, without getting carried away by them.</p>
      <h2 class="text-2xl font-headline mt-6 mb-3">Practical Tips for Digital Mindfulness</h2>
      <ul class="list-disc pl-6 mb-4">
        <li class="mb-2">Set designated "tech-free" times or zones.</li>
        <li class="mb-2">Practice mindful device usage: be intentional about why you're picking up your phone.</li>
        <li class="mb-2">Use apps for guided meditation, but don't let them become another source of distraction.</li>
        <li class="mb-2">Take short breaks throughout the day to simply breathe and observe your surroundings.</li>
      </ul>
      <p class="mb-4">Incorporating mindfulness into daily life doesn't require hours of meditation. Even a few minutes of conscious breathing can make a difference. It's about cultivating a new relationship with our thoughts, our technology, and the world around us.</p>
    `,
    excerpt: 'Discover practical strategies to foster mindfulness and reduce stress amidst the constant connectivity of the digital age, enhancing focus and emotional well-being.',
    tags: ['mindfulness', 'wellness', 'digital detox'],
  },
  {
    slug: 'the-art-of-storytelling',
    title: 'The Timeless Power of Storytelling in Communication',
    datePublished: '2024-07-05',
    author: 'Alice Brown',
    category: 'Creativity',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'open book campfire',
    content: `
      <p class="mb-4">From ancient campfires to modern boardrooms, storytelling has been a fundamental human way of connecting, teaching, and inspiring. A well-crafted narrative can captivate an audience, convey complex ideas simply, and evoke powerful emotions.</p>
      <h2 class="text-2xl font-headline mt-6 mb-3">Elements of a Great Story</h2>
      <p class="mb-4">Effective stories typically feature relatable characters, a clear conflict or challenge, and a satisfying resolution. They often tap into universal themes and emotions, making them resonate deeply with listeners or readers.</p>
      <p class="mb-4">In business, storytelling can be used to build brand identity, connect with customers on an emotional level, and motivate teams. In education, stories make learning more engaging and memorable. In personal life, sharing our stories helps us build relationships and understand ourselves better.</p>
      <h2 class="text-2xl font-headline mt-6 mb-3">Honing Your Storytelling Skills</h2>
      <p class="mb-4">Practice active listening to understand what resonates with others. Study the structure of compelling narratives in books, films, and talks. Most importantly, be authentic and passionate about the stories you tell. The power of storytelling lies in its ability to forge genuine human connections.</p>
    `,
    excerpt: 'Uncover the secrets behind effective storytelling and how this ancient art form remains a vital tool for connection, persuasion, and inspiration in all aspects of life.',
    tags: ['storytelling', 'communication', 'creativity'],
  },
  {
    slug: 'sustainable-travel-tips',
    title: 'Exploring the World Responsibly: A Guide to Sustainable Travel',
    datePublished: '2024-06-28',
    author: 'David Green',
    category: 'Travel',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'eco travel mountains',
    content: `
      <p class="mb-4">Travel broadens the mind, but it can also strain the environment and local communities. Sustainable travel aims to minimize negative impacts and maximize positive contributions, ensuring that destinations remain vibrant for future generations.</p>
      <h2 class="text-2xl font-headline mt-6 mb-3">Key Principles of Sustainable Travel</h2>
      <ul class="list-disc pl-6 mb-4">
        <li class="mb-2">Choose eco-friendly accommodations and transportation.</li>
        <li class="mb-2">Support local economies by buying local products and eating at local restaurants.</li>
        <li class="mb-2">Respect local cultures and traditions.</li>
        <li class="mb-2">Minimize waste: reduce, reuse, recycle.</li>
        <li class="mb-2">Conserve water and energy.</li>
      </ul>
      <p class="mb-4">Making conscious choices, even small ones, can collectively make a big difference. Researching destinations and tour operators for their sustainability practices is a good first step. Offsetting carbon emissions from flights is another way to mitigate environmental impact.</p>
      <p class="mb-4">Sustainable travel is not about sacrificing enjoyment; it's about enriching the travel experience by fostering deeper connections with places and people, while preserving the planet's beauty and diversity.</p>
    `,
    excerpt: 'Learn how to make your adventures more eco-friendly and culturally sensitive with these practical tips for sustainable travel, helping preserve our planet while you explore.',
    tags: ['sustainable travel', 'eco-tourism', 'responsible travel'],
  },
   {
    slug: 'urban-gardening-revolution',
    title: 'The Rise of Urban Gardening: Greening Concrete Jungles',
    datePublished: '2024-06-20',
    author: 'Chloe White',
    category: 'Lifestyle',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'rooftop garden city',
    content: `
      <p class="mb-4">As cities grow denser, the desire for green spaces and locally sourced food is fueling an urban gardening movement. From tiny balcony plots to sprawling rooftop farms, city dwellers are finding innovative ways to cultivate plants.</p>
      <h2 class="text-2xl font-headline mt-6 mb-3">Benefits Beyond the Harvest</h2>
      <p class="mb-4">Urban gardening offers more than just fresh produce. It beautifies urban landscapes, improves air quality, reduces the urban heat island effect, and provides habitats for pollinators. For individuals, it's a rewarding hobby that reduces stress and connects them with nature.</p>
      <h2 class="text-2xl font-headline mt-6 mb-3">Getting Started with Your Urban Garden</h2>
      <p class="mb-4">Space constraints are often the biggest challenge. Vertical gardens, container gardening, and hydroponic systems are popular solutions. Choosing plants suited to your climate and available sunlight is crucial. Community gardens also offer opportunities for those without private outdoor space.</p>
      <p class="mb-4">The urban gardening revolution is a testament to human ingenuity and our innate need to connect with the natural world. It's a green-thumbed rebellion against the gray of city life, one plant at a time.</p>
    `,
    excerpt: 'Discover the growing trend of urban gardening, transforming cityscapes with green oases and providing fresh, local food while fostering community and well-being.',
    tags: ['urban gardening', 'sustainability', 'lifestyle', 'DIY'],
  },
  {
    slug: 'the-power-of-habits',
    title: 'Unlocking Potential: How Habits Shape Our Lives',
    datePublished: '2024-06-12',
    author: 'Mark Persona',
    category: 'Self-Improvement',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'person goal setting',
    content: `
      <p class="mb-4">Our daily lives are largely a sum of our habits. These automated behaviors, both good and bad, significantly impact our health, productivity, and overall well-being. Understanding how habits are formed and how they can be changed is key to unlocking personal potential.</p>
      <h2 class="text-2xl font-headline mt-6 mb-3">The Habit Loop: Cue, Routine, Reward</h2>
      <p class="mb-4">Charles Duhigg, in "The Power of Habit," popularizes the concept of the habit loop: a cue triggers a routine, which leads to a reward. To change a habit, one often needs to identify these components and then modify the routine while keeping the cue and reward, or by finding a healthier reward.</p>
      <h2 class="text-2xl font-headline mt-6 mb-3">Strategies for Building Good Habits</h2>
      <ul class="list-disc pl-6 mb-4">
        <li class="mb-2">Start small: Tiny changes are easier to sustain and build upon.</li>
        <li class="mb-2">Be consistent: Repetition is crucial for automating a behavior.</li>
        <li class="mb-2">Track your progress: Visualizing success can be a powerful motivator.</li>
        <li class="mb-2">Find an accountability partner: Sharing goals can increase commitment.</li>
        <li class="mb-2">Don't get discouraged by setbacks: They are part of the process. Learn and readjust.</li>
      </ul>
      <p class="mb-4">By consciously shaping our habits, we can steer our lives in desired directions. It's a continuous process of self-awareness and intentional action, leading to lasting positive change.</p>
    `,
    excerpt: 'Delve into the science of habit formation and learn practical strategies to cultivate positive routines that can transform your productivity, health, and overall success.',
    tags: ['habits', 'self-improvement', 'productivity', 'psychology'],
  },
  // Adding more articles for categories to make pages more populated
  {
    slug: 'beginner-guide-to-investing',
    title: 'A Beginner\'s Guide to Investing in the Stock Market',
    datePublished: '2024-05-15',
    author: 'Sarah Coin',
    category: 'Finance',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'stock market chart',
    content: `<p>Investing can seem daunting, but it's a crucial step towards financial independence. This guide breaks down the basics for beginners.</p>`,
    excerpt: 'Navigate the world of stock market investing with this comprehensive guide for beginners, covering basics from choosing a broker to building a diversified portfolio.',
    tags: ['investing', 'finance', 'stocks', 'beginners'],
  },
  {
    slug: 'top-meditation-apps',
    title: 'Top 5 Meditation Apps for Stress Relief in 2024',
    datePublished: '2024-05-20',
    author: 'John Smith',
    category: 'Wellness',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'person meditating phone',
    content: `<p>Explore the best meditation apps to help you find calm and reduce stress in your daily life.</p>`,
    excerpt: 'Find your inner peace with our review of the top 5 meditation apps designed to help you de-stress, improve focus, and cultivate mindfulness anytime, anywhere.',
    tags: ['meditation', 'apps', 'wellness', 'stress relief'],
  },
  {
    slug: 'understanding-dog-behavior',
    title: 'Decoding Your Dog: Understanding Common Canine Behaviors',
    datePublished: '2024-05-10',
    author: 'Dr. Paw Some',
    category: 'Pets',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'dog playing park',
    content: `<p>Learn to understand what your furry friend is trying to tell you through their barks, tail wags, and body language.</p>`,
    excerpt: 'Unlock the secrets of your canine companion\'s behavior. This guide helps you understand common dog actions, from tail wags to barks, for a stronger bond.',
    tags: ['dogs', 'pets', 'animal behavior', 'training'],
  },
  {
    slug: 'electric-vehicle-maintenance',
    title: 'The Owner\'s Guide to Electric Vehicle (EV) Maintenance',
    datePublished: '2024-04-25',
    author: 'Gear Head',
    category: 'Automobile',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'electric car charging',
    content: `<p>EVs require different maintenance than traditional cars. Here’s what you need to know.</p>`,
    excerpt: 'Switching to an electric vehicle? Learn about the unique maintenance needs of EVs, from battery care to software updates, to keep your car running smoothly.',
    tags: ['electric vehicles', 'EV', 'automobile', 'maintenance'],
  },
  {
    slug: 'smart-online-shopping',
    title: '10 Tips for Smarter and Safer Online Shopping',
    datePublished: '2024-04-15',
    author: 'Savvy Shopper',
    category: 'Shopping',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'online shopping laptop',
    content: `<p>Online shopping is convenient, but it comes with risks. Shop smarter and safer with these tips.</p>`,
    excerpt: 'Maximize your online shopping experience with these 10 essential tips for finding the best deals, protecting your personal information, and avoiding common pitfalls.',
    tags: ['online shopping', 'ecommerce', 'safety', 'deals'],
  }
];

export function getAllArticles(): Article[] {
  return articles.sort((a, b) => new Date(b.datePublished).getTime() - new Date(a.datePublished).getTime());
}

export function getArticleBySlug(slug: string): Article | undefined {
  return articles.find(article => article.slug === slug);
}

export function getFeaturedArticle(): Article | undefined {
  return articles.find(article => article.isFeatured);
}

export function getPopularArticles(limit: number = 3): Article[] {
  // For mock data, we'll just take some non-featured articles.
  // In a real app, this would be based on views, shares, etc.
  return articles.filter(article => !article.isFeatured).slice(0, limit);
}

export function getRecentArticles(limit: number = 4, excludeSlug?: string): Article[] {
  return articles
    .filter(article => article.slug !== excludeSlug)
    .sort((a, b) => new Date(b.datePublished).getTime() - new Date(a.datePublished).getTime())
    .slice(0, limit);
}

export function searchArticles(query: string): Article[] {
  if (!query) return getAllArticles(); // Or an empty array if preferred for no query
  const lowerCaseQuery = query.toLowerCase();
  return articles.filter(article =>
    article.title.toLowerCase().includes(lowerCaseQuery) ||
    article.excerpt.toLowerCase().includes(lowerCaseQuery) ||
    (article.tags && article.tags.some(tag => tag.toLowerCase().includes(lowerCaseQuery))) ||
    article.category.toLowerCase().includes(lowerCaseQuery)
  );
}

export function getArticlesByCategory(categoryName: string): Article[] {
  const lowerCaseCategoryName = categoryName.toLowerCase();
  return articles
    .filter(article => article.category.toLowerCase() === lowerCaseCategoryName)
    .sort((a, b) => new Date(b.datePublished).getTime() - new Date(a.datePublished).getTime());
}

export function getAllUniqueCategories(): string[] {
  const categories = articles.map(article => article.category.toLowerCase());
  return [...new Set(categories)];
}
